version: '3'
services:
  influxdb: 
    image: influxdb
    container_name: influxdb
    volumes:
      - devnet-influxdb-data:/var/lib/influxdb:z
    networks:
     - DevNet
    ports:
      - 8086:8086

  grafana: 
    image: grafana/grafana
    container_name: grafana
    env_file: env/grafna.env
    volumes:
      - devnet-grafana-data:/var/lib/grafana
    networks:
     - DevNet
    ports:
      - 3000:3000

  rsyslog:
    image: b0066365/rsyslog:latest
    container_name: rsyslog
    command: rsyslogd -nf /etc/rsyslog.conf
    volumes:
      - $PWD/data/rsyslog/:/var/log/devnet
      - $PWD/conf/rsyslog/rsyslog.conf:/etc/rsyslog.conf:ro
    networks:
     - DevNet
    ports:
      - 514:514/udp

volumes:
  devnet-influxdb-data:
    driver: local
  devnet-grafana-data:
    driver: local
  devnet-syslog-data:
    driver: local
networks:
  DevNet:
