{
 "title": "FMC - Basic Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Ping", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Ping - Test Status",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_server",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "ping",
     "select": [
      [
       { "params": [ "result_code" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Ping - Avarage Response Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 3, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_url",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "url" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ping",
     "select": [
      [
       { "params": [ "average_response_ms" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "SSH", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "SSH - Test Status",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "alias": "$tag_server:$tag_port",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "port" ], "type": "tag" }
     ],
     "measurement": "net_response",
     "select": [
      [
       { "params": [ "result_code" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "port", "operator": "=", "value": "22" }
     ]
    }
   ]
  },
  {
   "title": "TCP - Response Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 3, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "$tag_server:$tag_port",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "port" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "net_response",
     "select": [
      [
       { "params": [ "response_time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "port", "operator": "=", "value": "22" }
     ]
    },
    {
     "alias": "$tag_server:$tag_port",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "port" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "net_response",
     "select": [
      [
       { "params": [ "response_time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "port", "operator": "=", "value": "8305" }
     ]
    }
   ]
  },
  {
   "title": "HTTP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTPS - Test Status",
     "type": "singlestat",
     "gridPos": { "h": 8, "w": 3, "x": 0, "y": 3 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "alias": "$tag_server:$tag_port",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "server" ], "type": "tag" },
        { "params": [ "port" ], "type": "tag" }
       ],
       "measurement": "http_response",
       "select": [
        [
         { "params": [ "result_code" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "HTTP - Response Time",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 3, "y": 3 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "alias": "$tag_server",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "server" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "http_response",
       "select": [
        [
         { "params": [ "response_time" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "HTTP - Response Code",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 3, "x": 15, "y": 3 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "alias": "$tag_server",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "server" ], "type": "tag" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "http_response",
       "select": [
        [
         { "params": [ "http_response_code" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Syslog",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Syslog Count",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "FMC",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "fmc_audit",
       "select": [
        [
         { "params": [ "message" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        {
         "key": "path",
         "operator": "=",
         "value": "/opt/devnet/data/rsyslog/devnet-fmc-01.log"
        }
       ]
      },
      {
       "alias": "FTD",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "fmc_audit",
       "select": [
        [
         { "params": [ "message" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        {
         "key": "path",
         "operator": "=",
         "value": "/opt/devnet/data/rsyslog/devnet-ftd-01.log"
        }
       ]
      },
      {
       "alias": "FTD - Blocked Sessions",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "fmc_audit",
       "query": "SELECT count(\"message\") FROM \"fmc_audit\" WHERE (\"path\" = '/opt/devnet/data/rsyslog/devnet-ftd-01.log') AND  (\"message\" =~ /Block/) AND $timeFilter GROUP BY time($__interval) fill(0)",
       "select": [
        [
         { "params": [ "message" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        {
         "key": "path",
         "operator": "=",
         "value": "/opt/devnet/data/rsyslog/devnet-ftd-01.log"
        }
       ]
      }
     ]
    },
    {
     "title": "FMC - Audit Log",
     "type": "table",
     "gridPos": { "h": 16, "w": 11, "x": 0, "y": 26 },
     "targets": [
      {
       "measurement": "fmc_audit",
       "select": [
        [
         { "params": [ "message" ], "type": "field" }
        ]
       ],
       "tags": [
        {
         "key": "path",
         "operator": "=",
         "value": "/opt/devnet/data/rsyslog/devnet-fmc-01.log"
        }
       ]
      }
     ]
    },
    {
     "title": "FTD - Log",
     "type": "table",
     "gridPos": { "h": 16, "w": 13, "x": 11, "y": 26 },
     "targets": [
      {
       "measurement": "fmc_audit",
       "select": [
        [
         { "params": [ "message" ], "type": "field" }
        ]
       ],
       "tags": [
        {
         "key": "path",
         "operator": "=",
         "value": "/opt/devnet/data/rsyslog/devnet-ftd-01.log"
        }
       ]
      }
     ]
    },
    {
     "title": "FTD - Hit Counts Test  - Log",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 42 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "measurement": "fmc_audit",
       "query": "SELECT count(\"message\") FROM \"fmc_audit\" WHERE (\"path\" = '/opt/devnet/data/rsyslog/devnet-ftd-01.log') AND  (\"message\" =~ /Ping/)  AND $timeFilter",
       "select": [
        [
         { "params": [ "message" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        {
         "key": "path",
         "operator": "=",
         "value": "/opt/devnet/data/rsyslog/devnet-ftd-01.log"
        }
       ]
      }
     ]
    },
    {
     "title": "FTD - Block Test  - Log",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 3, "x": 3, "y": 42 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "measurement": "fmc_audit",
       "query": "SELECT count(\"message\") FROM \"fmc_audit\" WHERE (\"path\" = '/opt/devnet/data/rsyslog/devnet-ftd-01.log') AND  (\"message\" =~ /Block/)  AND $timeFilter",
       "select": [
        [
         { "params": [ "message" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ]
       ],
       "tags": [
        {
         "key": "path",
         "operator": "=",
         "value": "/opt/devnet/data/rsyslog/devnet-ftd-01.log"
        }
       ]
      }
     ]
    },
    {
     "title": "FTD - Log - Blocked Sessions",
     "type": "table",
     "gridPos": { "h": 16, "w": 13, "x": 11, "y": 42 },
     "targets": [
      {
       "measurement": "fmc_audit",
       "query": "SELECT \"message\" FROM \"fmc_audit\" WHERE (\"path\" = '/opt/devnet/data/rsyslog/devnet-ftd-01.log') AND  (\"message\" =~ /Block/) AND $timeFilter",
       "select": [
        [
         { "params": [ "message" ], "type": "field" }
        ]
       ],
       "tags": [
        {
         "key": "path",
         "operator": "=",
         "value": "/opt/devnet/data/rsyslog/devnet-ftd-01.log"
        }
       ]
      }
     ]
    }
   ]
  }
 ]
}